
services:

  redis:
    image: redis
    ports:
      - "6379:6379"
      
  rabbitmq:
    image: rabbitmq:3.12.2-management
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672" 
